name: My first pipeline
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello! I am a robot running on GitHub's servers."
      - name: Check OS
        run: cat /etc/os-release
